#!/usr/bin/env python
# coding: utf-8

# ## Gaussian beam raytracing in KDP-2 / Koko

# How is Gaussian beam tracing performed in KDP-2? See this note of the manual:
# 
# "In many optical design and analysis programs, gaussian beam propagation is based upon a paraxial ray trace. This method is fast and
# simple but leaves much to be desired. The "paraxial" method can't be used in "decentered" optical system or in systems which contain
# diffractive optical elements. This program does not use this simplistic "paraxial" method but instead uses the "generalized paraxial ray
# trace" described earlier in this manual section. In the form of the "generalized paraxial ray trace" used for gaussian beam propagation, the
# gaussian beam divergence half-angle plays the role of a field angle to define the "generalized paraxial chief rays" and the gaussian beam
# semi-diameter on surface 1 plays the role of reference aperture height to define "generalized paraxial marginal rays". If surface 1 is not the
# system "reference surface" then it is temporarily redefined to be the system "reference surface" for all gaussian beam calculations. A field-of-
# view specification in the gaussian beam analysis commands acts to re-define the reference optical axis of the system for that particular
# ray trace by defining a new wavefront origin location on surface 0. The ray tracing performed is always exact, real, trigonometric ray
# tracing. The "generalized paraxial ray trace" is simulated by tracing real rays close to the central reference axis ray. The central reference
# axis ray is the ray that starts at the specified wavefront origin position on surface 0 and passes through the center of surface 1 (or the center
# of the clear aperture assigned to surface 1)."

# A "generalized paraxial ray trace" = real differential raytrace:
# 
# "Generalized paraxial data is generated by tracing real chief and marginal rays close to a chief ray and then scaling
# the resultant data up by the appropriate and current "SCX", "SCY", "SAX" and "SAY" values. For a centered systems with the reference
# surface assigned to the same surface as the aperture stop, a generalized paraxial ray trace along the optical axis will yield results identical
# to an ordinary first order paraxial ray trace."

# In[ ]:




